### ISSUE TITLE
Game Crash and other bugs on Chrome

### ISSUE THREAD

**Issue by StormWingDelta** [munificent/hauberk#47] opened 2018-11-13 16:07 UTC
Ran into this bug when trying to load up the level to play:
`Failed to load resource: the server responded with a status of 404 (Not Found)
main.dart.js:5016 Uncaught TypeError: Cannot read property '_sortOrder' of null
    at SlayDiscipline.compareTo$1 (main.dart.js:21098)
    at Object.J.compareTo$1$ns (main.dart.js:31990)
    at StaticClosure.dart.JSArray.static.JSArray__compareAny (main.dart.js:1023)
    at Object.Sort__insertionSort (main.dart.js:1544)
    at Object.Sort__doSort (main.dart.js:1532)
    at Object.Sort_sort (main.dart.js:1526)
    at Interceptor.sort$1 (main.dart.js:892)
    at Interceptor.sort$0 (main.dart.js:895)
    at SkillSet.get$discovered (main.dart.js:21217)
    at Hero.refreshProperties$0 (main.dart.js:20788)`

Also noticed that when exiting shops at the moment you don't move back a screen, but when you hit exit again you end up back at the character selection screen.

**Comment by munificent** [comment] 2018-11-14 01:03
Oops, thanks. I'll take a look.

**Comment by munificent** [comment] 2018-11-17 04:15
I can't reproduce either of these. I believe the first one is probably caused by having an older character with a skill whose name I changed or removed. That cause a null skill to get in and cause problems later. I added some better checking for that.

I can't repro the latter. Do you see anything in the dev console output when that happens? I'm going to close this for now becauseI don't have any ideas on how to take action, but I'll reopen it if you're still seeing it and can help me repro it.

**Closed by munificent** 2018-11-17 04:15 UTC
